services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    container_name: vital_backend
    volumes:
      - ./backend/data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - vital-net
    environment:
      - TZ=America/Argentina/Buenos_Aires

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vital_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - vital-net

networks:
  vital-net:
    driver: bridge